name: Deploy to Office Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd C:\projects\bmc-acms
          git pull origin main
          docker compose down
          docker compose up -d --build
